name: Package Release

on:
  release:
    types: [ published ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - name: Bump release version
        if: '!github.event.release.prerelease'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Bump pre-release version
        if: 'github.event.release.prerelease'
        run: npm publish --tag=next
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
